import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import * as p from '@clack/prompts'
import pc from 'picocolors'
import { loadSpec, saveSpec } from '../spec.js'
import type { ProjectSpec } from '@cinematic/core'

// Assets dir: dist/cli.js → packages/cli/ → assets/ (copied at build time by copy-assets.mjs)
const ASSETS_DIR = resolve(fileURLToPath(import.meta.url), '..', '..', 'assets')
const PROMPTS_DIR = join(ASSETS_DIR, 'prompts', 'product-development')

interface ThinkSession {
  brand: string
  purpose: string
  braindump: string
  valueProps?: [string, string, string]
  cta?: string
}

/**
 * Read a prompt template and fill in the brain dump placeholder.
 */
function fillTemplate(templatePath: string, session: ThinkSession): string {
  if (!existsSync(templatePath)) return ''
  const raw = readFileSync(templatePath, 'utf-8')

  const braindumpBlock = `
Brand: ${session.brand}
Purpose: ${session.purpose}
${session.valueProps ? `Value Propositions: ${session.valueProps.join(', ')}` : ''}
${session.cta ? `CTA: ${session.cta}` : ''}

---

${session.braindump}
`.trim()

  // Replace the placeholder block in the template
  return raw.replace(
    /\[\s*\*\*<<< PASTE YOUR RAW NOTES.*?>>>\*\*\s*\]/s,
    braindumpBlock
  )
}

/**
 * Generate a stub doc header when a template isn't found.
 */
function stubDoc(title: string, session: ThinkSession): string {
  return `# ${title}

**Brand:** ${session.brand}
**Purpose:** ${session.purpose}

> This document was generated by \`cinematic-web think\`.
> Paste this file's full contents into your LLM of choice to get started.

---

${session.braindump}
`
}

export async function runThink(): Promise<void> {
  p.intro(`${pc.bgCyan(pc.black(' cinematic-web '))} ${pc.dim('think')}`)

  const cwd = process.cwd()
  const existingSpec = loadSpec(cwd)

  p.note(
    [
      'The `think` command walks you through the product-development pipeline.',
      'It fills your brain dump into 5 prompt templates and writes them to docs/.',
      'Then paste each doc into Claude, GPT, or your LLM of choice to generate the artefacts.',
    ].join('\n'),
    'How this works'
  )

  // --- Brand ---
  const brandInput = await p.text({
    message: 'Brand name and one-line purpose?',
    placeholder: 'Nura Health — precision longevity medicine',
    initialValue: existingSpec ? `${existingSpec.brand} — ${existingSpec.purpose}` : '',
    validate: (v) => (v.trim().length === 0 ? 'Required' : undefined),
  })
  if (p.isCancel(brandInput)) { p.cancel('Cancelled.'); process.exit(0) }

  const brandStr = brandInput as string
  const dashIdx = brandStr.indexOf(' — ')
  const brand = dashIdx > -1 ? brandStr.slice(0, dashIdx).trim() : brandStr.trim()
  let purpose = dashIdx > -1 ? brandStr.slice(dashIdx + 3).trim() : ''

  if (!purpose) {
    const purposeInput = await p.text({
      message: 'One-line purpose?',
      placeholder: 'Precision longevity medicine powered by biological data.',
      validate: (v) => (v.trim().length === 0 ? 'Required' : undefined),
    })
    if (p.isCancel(purposeInput)) { p.cancel('Cancelled.'); process.exit(0) }
    purpose = (purposeInput as string).trim()
  }

  // --- Brain dump ---
  p.note(
    'Paste everything you know about this product — goals, features, competitors, users, constraints.\nNo need to structure it. Stream of consciousness is fine.',
    'Brain dump'
  )

  const braindumpInput = await p.text({
    message: 'Paste your brain dump',
    placeholder: 'We want to build a platform that...',
    validate: (v) => (v.trim().length < 20 ? 'Give me more to work with (20+ chars)' : undefined),
  })
  if (p.isCancel(braindumpInput)) { p.cancel('Cancelled.'); process.exit(0) }

  const session: ThinkSession = {
    brand,
    purpose,
    braindump: (braindumpInput as string).trim(),
  }

  // --- Optional value props ---
  const wantValueProps = await p.confirm({
    message: 'Do you know your 3 value propositions? (You can skip for now)',
    initialValue: !!existingSpec?.valueProps,
  })

  if (!p.isCancel(wantValueProps) && wantValueProps) {
    const vp0 = await p.text({
      message: 'Value prop 1',
      placeholder: 'Telemetry',
      initialValue: existingSpec?.valueProps[0] ?? '',
    })
    const vp1 = await p.text({
      message: 'Value prop 2',
      placeholder: 'Protocol',
      initialValue: existingSpec?.valueProps[1] ?? '',
    })
    const vp2 = await p.text({
      message: 'Value prop 3',
      placeholder: 'Outcomes',
      initialValue: existingSpec?.valueProps[2] ?? '',
    })

    if (!p.isCancel(vp0) && !p.isCancel(vp1) && !p.isCancel(vp2)) {
      session.valueProps = [
        (vp0 as string).trim() || 'Value Prop 1',
        (vp1 as string).trim() || 'Value Prop 2',
        (vp2 as string).trim() || 'Value Prop 3',
      ]
    }
  }

  // --- Optional CTA ---
  const ctaInput = await p.text({
    message: 'Primary CTA? (optional — press Enter to skip)',
    placeholder: 'Book a consultation',
    initialValue: existingSpec?.cta ?? '',
  })
  if (!p.isCancel(ctaInput) && (ctaInput as string).trim()) {
    session.cta = (ctaInput as string).trim()
  }

  // --- Write docs ---
  const spinner = p.spinner()
  spinner.start('Generating prompt templates in docs/…')

  const docsDir = join(cwd, 'docs')
  mkdirSync(docsDir, { recursive: true })

  const files: Array<{ templateFile: string; outputFile: string; title: string }> = [
    { templateFile: 'Guided-PRD-Creation.md', outputFile: 'PRD.md', title: 'Product Requirements Document' },
    { templateFile: 'Guided-UX-User-Flow.md', outputFile: 'UX.md', title: 'UX & User Flow' },
    { templateFile: 'Guided-MVP-Concept.md', outputFile: 'MVP-Concept.md', title: 'MVP Concept' },
    { templateFile: 'Guided-MVP.md', outputFile: 'MVP.md', title: 'MVP Plan' },
    { templateFile: 'Guided-Test-Plan.md', outputFile: 'Test-Plan.md', title: 'Test Plan' },
  ]

  const written: string[] = []

  for (const { templateFile, outputFile, title } of files) {
    const templatePath = join(PROMPTS_DIR, templateFile)
    const outputPath = join(docsDir, outputFile)

    const content = existsSync(templatePath)
      ? fillTemplate(templatePath, session)
      : stubDoc(title, session)

    writeFileSync(outputPath, content, 'utf-8')
    written.push(`docs/${outputFile}`)
  }

  // --- Update cinematic.json ---
  const partialSpec: Partial<ProjectSpec> & Pick<ProjectSpec, 'brand' | 'purpose' | 'presetId' | 'valueProps' | 'cta' | 'notes'> = {
    brand,
    purpose,
    presetId: existingSpec?.presetId ?? 'organic-tech',
    valueProps: session.valueProps ?? existingSpec?.valueProps ?? ['Value 1', 'Value 2', 'Value 3'],
    cta: session.cta ?? existingSpec?.cta ?? 'Get started',
    notes: existingSpec?.notes ?? '',
    prd: { path: './docs/PRD.md' },
    ux: { path: './docs/UX.md' },
    mvp: { path: './docs/MVP.md' },
  }

  saveSpec(partialSpec as ProjectSpec, cwd)

  spinner.stop(`${pc.green('✓')} Generated ${written.length} prompt templates`)

  // --- Summary ---
  p.note(
    written.map((f) => `${pc.cyan(f)}`).join('\n'),
    'Files written'
  )

  p.note(
    [
      `1. Open each doc in ${pc.cyan('docs/')} with your LLM (Claude, GPT, Gemini, etc.)`,
      '2. The brain dump is pre-filled — just send the doc as your first message.',
      '3. Work through PRD → UX → MVP → Test Plan in order.',
      `4. When ready to build: ${pc.cyan('cinematic-web create')} will pre-fill from ${pc.cyan('cinematic.json')}`,
    ].join('\n'),
    'Next steps'
  )

  p.outro(`${pc.green('Done!')} Your product docs are in ${pc.cyan('docs/')}`)
}
