/**
 * sync-claude.ts
 * Regenerates the "## Aesthetic Presets" section in CLAUDE.md from presets/<id>/preset.json.
 * Keeps CLAUDE.md (prompt-mode) in sync with the CLI preset registry.
 *
 * Usage: pnpm sync:claude
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { resolve, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(__dirname, '..')

// Ordered preset list matches CLAUDE.md display order
const PRESET_ORDER = [
  'organic-tech',
  'midnight-luxe',
  'brutalist-signal',
  'vapor-clinic',
  'antigravity-lift',
  '3d-immersive',
]

const PRESET_LETTERS = ['A', 'B', 'C', 'D', 'E', 'F']

interface PresetJson {
  id: string
  name: string
  label: string
  template: string
  identity: string
  palette: {
    primary: string
    accent: string
    background: string
    dark: string
    primaryLabel: string
    accentLabel: string
    backgroundLabel: string
    darkLabel: string
  }
  typography: {
    heading: string[]
    drama?: string
    data?: string
    headingTracking?: string
    dramaStyle?: string
  }
  imageMood: string
  heroLinePattern?: {
    part1: string
    part1Style: string
    part2: string
    part2Style: string
  }
}

function loadPresets(): PresetJson[] {
  return PRESET_ORDER.map((id) => {
    const path = join(REPO_ROOT, 'presets', id, 'preset.json')
    return JSON.parse(readFileSync(path, 'utf-8')) as PresetJson
  })
}

function formatTypography(t: PresetJson['typography']): string {
  const headings = t.heading.map((h) => `"${h}"`).join(' + ')
  const trackingNote = t.headingTracking ? ` (${t.headingTracking} tracking)` : ''
  const dramaNote = t.drama ? `. Drama: "${t.drama}"${t.dramaStyle === 'italic' ? ' Italic' : ''}` : ''
  const dataNote = t.data ? `. Data: \`"${t.data}"\`` : ''
  return `Headings: ${headings}${trackingNote}${dramaNote}${dataNote}.`
}

function formatPalette(p: PresetJson['palette']): string {
  return (
    `${p.primaryLabel} \`${p.primary}\` (Primary), ` +
    `${p.accentLabel} \`${p.accent}\` (Accent), ` +
    `${p.backgroundLabel} \`${p.background}\` (Background), ` +
    `${p.darkLabel} \`${p.dark}\` (Text/Dark)`
  )
}

function generatePresetBlock(preset: PresetJson, letter: string): string {
  const lines: string[] = []
  lines.push(`### Preset ${letter} — "${preset.name}" (${preset.label})`)
  lines.push(`- **Identity:** ${preset.identity}`)
  lines.push(`- **Palette:** ${formatPalette(preset.palette)}`)
  lines.push(`- **Typography:** ${formatTypography(preset.typography)}`)
  lines.push(`- **Image Mood:** ${preset.imageMood}.`)

  if (preset.heroLinePattern) {
    const { part1, part1Style, part2, part2Style } = preset.heroLinePattern
    lines.push(
      `- **Hero line pattern:** "${part1}" (${part1Style.replace(/ /g, ' ')}) / "${part2}" (${part2Style.replace(/ /g, ' ')})`,
    )
  } else if (preset.template === 'three-fiber') {
    lines.push(`- See: \`prompts/3d-immersive/3d-website-builder.md\` for the complete 3D build system.`)
    lines.push(`- Use React Three Fiber + Drei + GSAP ScrollTrigger + Lenis smooth scroll.`)
  }

  return lines.join('\n')
}

function generatePresetsSection(presets: PresetJson[]): string {
  const intro =
    'Each preset defines: `palette`, `typography`, `identity` (the overall feel), and `imageMood` (Unsplash search keywords for hero/texture images).'

  const blocks = presets.map((p, i) => generatePresetBlock(p, PRESET_LETTERS[i])).join('\n\n')

  // Marker comments delimit the auto-generated region
  return [
    '## Aesthetic Presets',
    '',
    intro,
    '',
    '<!-- PRESETS:START — auto-generated by scripts/sync-claude.ts, do not edit manually -->',
    blocks,
    '<!-- PRESETS:END -->',
  ].join('\n')
}

function updateClaudeMd(newSection: string): void {
  const claudePath = join(REPO_ROOT, 'CLAUDE.md')
  const content = readFileSync(claudePath, 'utf-8')

  // Strategy 1: replace between marker comments (after first sync run)
  const markerPattern =
    /(## Aesthetic Presets[\s\S]*?<!-- PRESETS:START[^>]*>)([\s\S]*?)(<!-- PRESETS:END -->)/

  // Strategy 2: replace entire ## Aesthetic Presets section (before first sync run)
  // Match from the heading until the next ## heading
  const sectionPattern = /## Aesthetic Presets[\s\S]*?(?=\n## )/

  let updated: string

  if (markerPattern.test(content)) {
    // Already has markers — replace the section wholesale
    updated = content.replace(markerPattern, newSection)
  } else if (sectionPattern.test(content)) {
    // First run — no markers yet, replace the raw section
    updated = content.replace(sectionPattern, newSection + '\n\n')
  } else {
    console.error('ERROR: Could not locate "## Aesthetic Presets" section in CLAUDE.md')
    process.exit(1)
  }

  writeFileSync(claudePath, updated, 'utf-8')
}

function main(): void {
  const presets = loadPresets()
  console.log(`Loaded ${presets.length} presets: ${presets.map((p) => p.id).join(', ')}`)

  const section = generatePresetsSection(presets)
  updateClaudeMd(section)

  console.log('✓ CLAUDE.md presets section updated')
}

main()
